server {
    listen                     127.0.0.1:8001 http2 ssl;
    client_max_body_size 512m;

    ssl_protocols              TLSv1.2 TLSv1.3;
    ssl_ciphers                TLS13_AES_128_GCM_SHA256:TLS13_AES_256_GCM_SHA384:TLS13_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers  on;

    ssl_stapling               on;
    ssl_stapling_verify        on;
    ssl_session_timeout 5m;
    resolver                   1.1.1.1 valid=60s;
    resolver_timeout           60s;

    server_name {domain};
    ssl_certificate  cert/{cert_name}.pem;
    ssl_certificate_key cert/{cert_name}.key;

    location / {
        root {static_root_path};
        index index.html;
    }
}
